export const iceServers = [
  'stun:stun.qq.com',
  // 'stun:stunserver.org',
  // 'stun:stun.voxgratia.org',
  // 'stun:stun.ideasip.com',
  // 'stun:stun.voiparound.com',
  // 'stun:stun.voipbuster.com',
  // 'stun:stun.voipstunt.com',
  // 'stun:stun.1und1.de',
  // 'stun:stun.gmx.net',
  // 'stun:stun.callwithus.com',
  // 'stun:stun.counterpath.net',
  // 'stun:stun.internetcalls.com',
  // 'stun:stun01.sipphone.com',
  // 'stun:stun.ekiga.net',
  // 'stun:stun.fwdnet.net',
  // 'stun:stun.iptel.org',
  // 'stun:stun.rixtelecom.se',
  // 'stun:stun.schlund.de',
  // 'stun:stun.softjoys.com',
  // 'stun:stun.xten.com',
]
