import { AuthlibInjectorService, BaseService, CurseForgeService, YggdrasilService, ImportService, InstallService, InstanceIOService, InstanceInstallService, InstanceLogService, InstanceManifestService, InstanceModsService, InstanceOptionsService, InstanceResourcePackService, InstanceSavesService, InstanceScreenshotService, InstanceService, InstanceShaderPacksService, InstanceUpdateService, InstanceVersionService, JavaService, LaunchService, LittleSkinUserService, ModpackService, ModrinthService, NatService, OfficialUserService, PeerService, PresenceService, ResourcePackPreviewService, ResourceService, ServerStatusService, UserService, VersionService } from '@xmcl/runtime'

export const definedServices = [
  LittleSkinUserService,
  BaseService,
  CurseForgeService,
  AuthlibInjectorService,
  ImportService,
  NatService,
  InstallService,
  InstanceIOService,
  InstanceLogService,
  InstanceModsService,
  InstanceOptionsService,
  InstanceResourcePackService,
  InstanceSavesService,
  InstanceService,
  InstanceScreenshotService,
  InstanceShaderPacksService,
  InstanceUpdateService,
  PresenceService,
  InstanceVersionService,
  JavaService,
  LaunchService,
  ModpackService,
  ModrinthService,
  ResourcePackPreviewService,
  ResourceService,
  InstanceManifestService,
  ServerStatusService,
  OfficialUserService,
  UserService,
  VersionService,
  YggdrasilService,
  InstanceInstallService,
  PeerService,
]
