import { BaseService, CurseForgeService, YggdrasilUserService, LittleSkinUserService, DiagnoseService, ExternalAuthSkinService, FeedTheBeastService, ImportService, InstallService, InstanceIOService, InstanceJavaService, InstanceLogService, InstanceModsService, InstanceOptionsService, InstanceResourcePackService, InstanceSavesService, InstanceService, InstanceShaderPacksService, InstanceVersionService, JavaService, LaunchService, OfficialUserService, ModpackService, ModrinthService, PeerService, ResourcePackPreviewService, ResourceService, ServerStatusService, UserService, VersionService, InstanceInstallService } from '@xmcl/runtime'

export const preloadServices = [
  LittleSkinUserService,
  BaseService,
  CurseForgeService,
  DiagnoseService,
  ExternalAuthSkinService,
  ImportService,
  InstallService,
  InstanceIOService,
  InstanceJavaService,
  InstanceLogService,
  InstanceModsService,
  InstanceOptionsService,
  InstanceResourcePackService,
  InstanceSavesService,
  InstanceService,
  InstanceShaderPacksService,
  InstanceVersionService,
  JavaService,
  LaunchService,
  ModpackService,
  ModrinthService,
  ResourcePackPreviewService,
  ResourceService,
  ServerStatusService,
  YggdrasilUserService,
  OfficialUserService,
  UserService,
  VersionService,
  FeedTheBeastService,
  InstanceInstallService,
  PeerService,
]
