[package]
name = "xmcl-tauri-app"
version = "0.66.2"
description = "XMCL - An open-source launcher for Minecraft (Tauri shell)"
authors = ["ci010 <cijhn@hotmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.85"

[lib]
name = "xmcl_tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
tauri-plugin-deep-link = "2.4.9"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
