// Code generated by scripts/gen-go-contract.ts. DO NOT EDIT.

// Package services aggregates every concrete service implementation
// behind a single RegisterAll call.
package services

import (
	"github.com/voxelum/xmcl/wails/internal/bridge"
	"github.com/voxelum/xmcl/wails/internal/contract"
	"github.com/voxelum/xmcl/wails/internal/host"

	appssvc "github.com/voxelum/xmcl/wails/internal/services/apps"
	authlibinjectorsvc "github.com/voxelum/xmcl/wails/internal/services/authlibinjector"
	basesvc "github.com/voxelum/xmcl/wails/internal/services/base"
	bootstrapsvc "github.com/voxelum/xmcl/wails/internal/services/bootstrap"
	elybysvc "github.com/voxelum/xmcl/wails/internal/services/elyby"
	installsvc "github.com/voxelum/xmcl/wails/internal/services/install"
	instanceinstallsvc "github.com/voxelum/xmcl/wails/internal/services/instanceinstall"
	instanceiosvc "github.com/voxelum/xmcl/wails/internal/services/instanceio"
	instancelogsvc "github.com/voxelum/xmcl/wails/internal/services/instancelog"
	instancemanagingsvc "github.com/voxelum/xmcl/wails/internal/services/instancemanaging"
	instancemanifestsvc "github.com/voxelum/xmcl/wails/internal/services/instancemanifest"
	instancemodsgroupsvc "github.com/voxelum/xmcl/wails/internal/services/instancemodsgroup"
	instancemodssvc "github.com/voxelum/xmcl/wails/internal/services/instancemods"
	instanceoptionssvc "github.com/voxelum/xmcl/wails/internal/services/instanceoptions"
	instanceresourcepackssvc "github.com/voxelum/xmcl/wails/internal/services/instanceresourcepacks"
	instanceresourcessvc "github.com/voxelum/xmcl/wails/internal/services/instanceresources"
	instancesavessvc "github.com/voxelum/xmcl/wails/internal/services/instancesaves"
	instancescreenshotsvc "github.com/voxelum/xmcl/wails/internal/services/instancescreenshot"
	instanceserverinfosvc "github.com/voxelum/xmcl/wails/internal/services/instanceserverinfo"
	instancesvc "github.com/voxelum/xmcl/wails/internal/services/instance"
	instanceshaderpackssvc "github.com/voxelum/xmcl/wails/internal/services/instanceshaderpacks"
	instancethemesvc "github.com/voxelum/xmcl/wails/internal/services/instancetheme"
	javasvc "github.com/voxelum/xmcl/wails/internal/services/java"
	launchsvc "github.com/voxelum/xmcl/wails/internal/services/launch"
	littleskinusersvc "github.com/voxelum/xmcl/wails/internal/services/littleskinuser"
	migrationsvc "github.com/voxelum/xmcl/wails/internal/services/migration"
	modmetadatasvc "github.com/voxelum/xmcl/wails/internal/services/modmetadata"
	modpacksvc "github.com/voxelum/xmcl/wails/internal/services/modpack"
	officialusersvc "github.com/voxelum/xmcl/wails/internal/services/officialuser"
	peersvc "github.com/voxelum/xmcl/wails/internal/services/peer"
	presencesvc "github.com/voxelum/xmcl/wails/internal/services/presence"
	projectmappingsvc "github.com/voxelum/xmcl/wails/internal/services/projectmapping"
	resourcepackpreviewsvc "github.com/voxelum/xmcl/wails/internal/services/resourcepackpreview"
	serverstatussvc "github.com/voxelum/xmcl/wails/internal/services/serverstatus"
	tasksvc "github.com/voxelum/xmcl/wails/internal/services/task"
	themesvc "github.com/voxelum/xmcl/wails/internal/services/theme"
	usersvc "github.com/voxelum/xmcl/wails/internal/services/user"
	versionmetadatasvc "github.com/voxelum/xmcl/wails/internal/services/versionmetadata"
	versionsvc "github.com/voxelum/xmcl/wails/internal/services/version"
	windowsvc "github.com/voxelum/xmcl/wails/internal/services/window"
	xupdatesvc "github.com/voxelum/xmcl/wails/internal/services/xupdate"
)

// RegisterAll wires every service into the bridge. Should be called
// AFTER contract.RegisterStubs(b) so real adapters overwrite the
// "not implemented" stubs.
func RegisterAll(b *bridge.Bridge, h *host.Host) {
	b.Register("AppsService", contract.NewAppsServiceAdapter(appssvc.New(h, b.States())))
	b.Register("AuthlibInjectorService", contract.NewAuthlibInjectorServiceAdapter(authlibinjectorsvc.New(h, b.States())))
	b.Register("BaseService", contract.NewBaseServiceAdapter(basesvc.New(h, b.States())))
	b.Register("BootstrapService", contract.NewBootstrapServiceAdapter(bootstrapsvc.New(h, b.States())))
	b.Register("ElyByService", contract.NewElyByServiceAdapter(elybysvc.New(h, b.States())))
	b.Register("InstallService", contract.NewInstallServiceAdapter(installsvc.New(h, b.States())))
	b.Register("InstanceInstallService", contract.NewInstanceInstallServiceAdapter(instanceinstallsvc.New(h, b.States())))
	b.Register("InstanceIOService", contract.NewInstanceIOServiceAdapter(instanceiosvc.New(h, b.States())))
	b.Register("InstanceLogService", contract.NewInstanceLogServiceAdapter(instancelogsvc.New(h, b.States())))
	b.Register("InstanceManagingService", contract.NewInstanceManagingServiceAdapter(instancemanagingsvc.New(h, b.States())))
	b.Register("InstanceManifestService", contract.NewInstanceManifestServiceAdapter(instancemanifestsvc.New(h, b.States())))
	b.Register("InstanceModsGroupService", contract.NewInstanceModsGroupServiceAdapter(instancemodsgroupsvc.New(h, b.States())))
	b.Register("InstanceModsService", contract.NewInstanceModsServiceAdapter(instancemodssvc.New(h, b.States())))
	b.Register("InstanceOptionsService", contract.NewInstanceOptionsServiceAdapter(instanceoptionssvc.New(h, b.States())))
	b.Register("InstanceResourcePacksService", contract.NewInstanceResourcePacksServiceAdapter(instanceresourcepackssvc.New(h, b.States())))
	b.Register("InstanceResourcesService", contract.NewInstanceResourcesServiceAdapter(instanceresourcessvc.New(h, b.States())))
	b.Register("InstanceSavesService", contract.NewInstanceSavesServiceAdapter(instancesavessvc.New(h, b.States())))
	b.Register("InstanceScreenshotService", contract.NewInstanceScreenshotServiceAdapter(instancescreenshotsvc.New(h, b.States())))
	b.Register("InstanceServerInfoService", contract.NewInstanceServerInfoServiceAdapter(instanceserverinfosvc.New(h, b.States())))
	b.Register("InstanceService", contract.NewInstanceServiceAdapter(instancesvc.New(h, b.States())))
	b.Register("InstanceShaderPacksService", contract.NewInstanceShaderPacksServiceAdapter(instanceshaderpackssvc.New(h, b.States())))
	b.Register("InstanceThemeService", contract.NewInstanceThemeServiceAdapter(instancethemesvc.New(h, b.States())))
	b.Register("JavaService", contract.NewJavaServiceAdapter(javasvc.New(h, b.States())))
	b.Register("LaunchService", contract.NewLaunchServiceAdapter(launchsvc.New(h, b.States())))
	b.Register("LittleSkinUserService", contract.NewLittleSkinUserServiceAdapter(littleskinusersvc.New(h, b.States())))
	b.Register("MigrationService", contract.NewMigrationServiceAdapter(migrationsvc.New(h, b.States())))
	b.Register("ModMetadataService", contract.NewModMetadataServiceAdapter(modmetadatasvc.New(h, b.States())))
	b.Register("ModpackService", contract.NewModpackServiceAdapter(modpacksvc.New(h, b.States())))
	b.Register("OfficialUserService", contract.NewOfficialUserServiceAdapter(officialusersvc.New(h, b.States())))
	b.Register("PeerService", contract.NewPeerServiceAdapter(peersvc.New(h, b.States())))
	b.Register("PresenceService", contract.NewPresenceServiceAdapter(presencesvc.New(h, b.States())))
	b.Register("ProjectMappingService", contract.NewProjectMappingServiceAdapter(projectmappingsvc.New(h, b.States())))
	b.Register("ResourcePackPreviewService", contract.NewResourcePackPreviewServiceAdapter(resourcepackpreviewsvc.New(h, b.States())))
	b.Register("ServerStatusService", contract.NewServerStatusServiceAdapter(serverstatussvc.New(h, b.States())))
	b.Register("TaskService", contract.NewTaskServiceAdapter(tasksvc.New(h, b.States())))
	b.Register("ThemeService", contract.NewThemeServiceAdapter(themesvc.New(h, b.States())))
	b.Register("UserService", contract.NewUserServiceAdapter(usersvc.New(h, b.States())))
	b.Register("VersionMetadataService", contract.NewVersionMetadataServiceAdapter(versionmetadatasvc.New(h, b.States())))
	b.Register("VersionService", contract.NewVersionServiceAdapter(versionsvc.New(h, b.States())))
	b.Register("WindowService", contract.NewWindowServiceAdapter(windowsvc.New(h, b.States())))
	b.Register("XUpdateService", contract.NewXUpdateServiceAdapter(xupdatesvc.New(h, b.States())))
}
