import { timingSafeEqual } from 'crypto'
import { EventEmitter } from 'events'
import { createServer, IncomingMessage, Server } from 'http'
import { AddressInfo } from 'net'
import { Duplex } from 'stream'
import { WebSocket, WebSocketServer } from 'ws'
import {
  BRIDGE_PATH,
  ClientMessage,
  EventMessage,
  MissingHandlerError,
  ReplyMessage,
  serializeError,
} from '../../bridge/protocol'

/**
 * The renderer connection, as `xmcl-runtime` knows it. It is the sidecar's
 * replacement for Electron's `WebContents`: services keep it to push state
 * mutations to the window that subscribed to them.
 */
export class BridgeClient extends EventEmitter {
  constructor(private readonly ws: WebSocket, private readonly server: BridgeServer) {
    super()
  }

  isDestroyed() {
    return this.ws.readyState !== WebSocket.OPEN && this.ws.readyState !== WebSocket.CONNECTING
  }

  send(channel: string, ...payload: any[]) {
    this.server.sendTo(this.ws, channel, payload)
  }
}

export interface BridgeEvent {
  sender: BridgeClient
}

export type BridgeHandler = (event: BridgeEvent, ...args: any[]) => unknown

/**
 * Local RPC endpoint replacing Electron's intra-process IPC.
 *
 * Security notes, because moving IPC to a socket is a real regression surface:
 * the server binds loopback only, requires the per-launch token generated by
 * the Rust shell, and rejects cross-origin upgrades. A single WebSocket server
 * handles the upgrade manually: attaching several `WebSocketServer`s with
 * different `path`s to one HTTP server makes them race on the handshake.
 */
export class BridgeServer {
  private readonly handlers = new Map<string, { handler: BridgeHandler; once: boolean }>()
  private readonly clients = new Map<WebSocket, BridgeClient>()
  private readonly wss = new WebSocketServer({ noServer: true, maxPayload: 128 * 1024 * 1024 })
  private readonly http: Server = createServer((_, res) => {
    res.writeHead(404).end()
  })

  constructor(private readonly token: string, private readonly logger: Pick<Console, 'log' | 'warn' | 'error'> = console) {
    this.http.on('upgrade', (req, socket, head) => this.onUpgrade(req, socket, head))
    this.wss.on('connection', (ws) => this.onConnection(ws))
  }

  /** Register a channel, mirroring `ipcMain.handle`. */
  handle(channel: string, handler: BridgeHandler) {
    this.handlers.set(channel, { handler, once: false })
    return this
  }

  /** Register a channel consumed by the first call, like `ipcMain.handleOnce`. */
  handleOnce(channel: string, handler: BridgeHandler) {
    this.handlers.set(channel, { handler, once: true })
    return this
  }

  removeHandler(channel: string) {
    this.handlers.delete(channel)
    return this
  }

  /** Push an event to every connected window, like `webContents.send`. */
  broadcast(channel: string, ...args: unknown[]) {
    const message: EventMessage = { t: 'event', channel, args }
    const payload = JSON.stringify(message)
    for (const client of this.clients.keys()) {
      this.send(client, payload)
    }
  }

  /** Push an event to a single window, like `webContents.send`. */
  sendTo(client: WebSocket, channel: string, args: unknown[]) {
    const message: EventMessage = { t: 'event', channel, args }
    this.send(client, JSON.stringify(message))
  }

  get clientCount() {
    return this.clients.size
  }

  async listen(port: number) {
    await new Promise<void>((resolve, reject) => {
      this.http.once('error', reject)
      this.http.listen(port, '127.0.0.1', () => {
        this.http.removeListener('error', reject)
        resolve()
      })
    })
    return (this.http.address() as AddressInfo).port
  }

  async close() {
    for (const client of this.clients.keys()) client.close()
    this.clients.clear()
    await new Promise<void>((resolve) => this.http.close(() => resolve()))
  }

  /**
   * `libdatachannel`-style backpressure lesson applies here too: a webview
   * that stops reading must not grow the send buffer without bound. Drop the
   * connection instead of letting the sidecar's heap follow it.
   */
  private send(client: WebSocket, payload: string) {
    if (client.readyState !== WebSocket.OPEN) return
    if (client.bufferedAmount > 64 * 1024 * 1024) {
      this.logger.warn('[bridge] client is not draining; closing it')
      client.terminate()
      return
    }
    client.send(payload)
  }

  private onUpgrade(req: IncomingMessage, socket: Duplex, head: Buffer) {
    const reject = (reason: string) => {
      this.logger.warn(`[bridge] rejected upgrade: ${reason}`)
      socket.destroy()
    }
    const remote = req.socket.remoteAddress ?? ''
    if (remote !== '127.0.0.1' && remote !== '::1' && remote !== '::ffff:127.0.0.1') {
      return reject(`non-loopback peer ${remote}`)
    }
    const url = new URL(req.url ?? '/', 'http://127.0.0.1')
    if (url.pathname !== BRIDGE_PATH) {
      return reject(`unknown path ${url.pathname}`)
    }
    if (!this.isAuthorized(url.searchParams.get('token'))) {
      return reject('invalid token')
    }
    this.wss.handleUpgrade(req, socket, head, (ws) => this.wss.emit('connection', ws, req))
  }

  private isAuthorized(token: string | null) {
    if (!token) return false
    const expected = Buffer.from(this.token)
    const actual = Buffer.from(token)
    return expected.length === actual.length && timingSafeEqual(expected, actual)
  }

  private onConnection(ws: WebSocket) {
    const client = new BridgeClient(ws, this)
    this.clients.set(ws, client)
    this.logger.log(`[bridge] window connected (${this.clients.size} total)`)
    ws.on('close', () => {
      this.clients.delete(ws)
      client.emit('destroyed')
      this.logger.log(`[bridge] window disconnected (${this.clients.size} left)`)
    })
    ws.on('error', (e) => this.logger.warn(`[bridge] socket error: ${e.message}`))
    ws.on('message', (data, isBinary) => {
      if (isBinary) {
        this.logger.warn('[bridge] ignoring binary frame')
        return
      }
      let message: ClientMessage
      try {
        message = JSON.parse(data.toString())
      } catch {
        this.logger.warn('[bridge] ignoring malformed frame')
        return
      }
      void this.dispatch(ws, message)
    })
  }

  private async dispatch(ws: WebSocket, message: ClientMessage) {
    if (typeof message?.channel !== 'string' || !Array.isArray(message.args)) {
      this.logger.warn('[bridge] ignoring frame with an invalid shape')
      return
    }
    if (message.t === 'send') {
      await this.call(ws, message.channel, message.args).catch((e) =>
        this.logger.error(`[bridge] '${message.channel}' failed: ${e?.message ?? e}`),
      )
      return
    }
    if (message.t !== 'invoke' || typeof message.id !== 'number') {
      this.logger.warn('[bridge] ignoring frame with an unknown type')
      return
    }
    let reply: ReplyMessage
    try {
      reply = { t: 'reply', id: message.id, ok: true, result: await this.call(ws, message.channel, message.args) }
    } catch (e) {
      reply = { t: 'reply', id: message.id, ok: false, error: serializeError(e) }
    }
    this.send(ws, JSON.stringify(reply))
  }

  private async call(ws: WebSocket, channel: string, args: unknown[]) {
    const entry = this.handlers.get(channel)
    if (!entry) throw new MissingHandlerError(channel)
    if (entry.once) this.handlers.delete(channel)
    const sender = this.clients.get(ws)
    if (!sender) throw new Error(`The client of '${channel}' is gone`)
    return await entry.handler({ sender }, ...args)
  }
}
