/**
 * gen-testids.ts — scan all xmcl-keystone-ui Vue components for
 * `data-testid="…"` and write a sorted Markdown registry to
 * `e2e/TESTIDS.md`.
 *
 * The registry is the contract between the launcher's UI and the e2e suite.
 * AGENTS.md points the Copilot agent here so it can discover existing
 * anchors before writing a scratch spec.
 *
 * Usage:
 *   pnpm gen:testids
 *
 * Run on pre-commit (or in CI guard) to keep the file fresh.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..')
const SOURCE_ROOT = resolve(REPO_ROOT, 'xmcl-keystone-ui/src')
const OUTPUT = resolve(REPO_ROOT, 'e2e/TESTIDS.md')

interface Hit {
  testid: string
  file: string
  line: number
}

async function walk(dir: string, out: string[] = []): Promise<string[]> {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue
      await walk(p, out)
    } else if (entry.isFile() && entry.name.endsWith('.vue')) {
      out.push(p)
    }
  }
  return out
}

const TESTID_RE = /data-testid\s*=\s*"([a-z0-9-]+)"/gi

async function main(): Promise<void> {
  const files = await walk(SOURCE_ROOT)
  const hits: Hit[] = []

  for (const file of files) {
    const text = await readFile(file, 'utf8')
    const lines = text.split(/\r?\n/)
    lines.forEach((line, i) => {
      let m: RegExpExecArray | null
      TESTID_RE.lastIndex = 0
      while ((m = TESTID_RE.exec(line)) !== null) {
        hits.push({ testid: m[1], file, line: i + 1 })
      }
    })
  }

  const grouped = new Map<string, Hit[]>()
  for (const h of hits) {
    const list = grouped.get(h.testid) ?? []
    list.push(h)
    grouped.set(h.testid, list)
  }

  const sortedIds = [...grouped.keys()].sort()

  const lines: string[] = []
  lines.push('# `data-testid` registry')
  lines.push('')
  lines.push('> **Auto-generated by `pnpm gen:testids`.** Do not edit by hand.')
  lines.push('')
  lines.push(
    'This file is the contract between the launcher UI in `xmcl-keystone-ui/` and the Playwright e2e suite. ' +
      'When you write a Playwright spec (or a scratch spec for visual verification), prefer ' +
      '`getByTestId(...)` selectors from this list over class names or text content.',
  )
  lines.push('')
  lines.push('If the anchor you need is not here, add a `data-testid="…"` attribute to the corresponding Vue component, then re-run `pnpm gen:testids`.')
  lines.push('')
  lines.push(`**Total anchors:** ${sortedIds.length} (in ${files.length} Vue files)`)
  lines.push('')
  lines.push('| Test ID | Defined in |')
  lines.push('|---|---|')

  for (const id of sortedIds) {
    const where = (grouped.get(id) ?? [])
      .map((h) => {
        const rel = relative(REPO_ROOT, h.file).replace(/\\/g, '/')
        return `[\`${rel}#L${h.line}\`](../${rel}#L${h.line})`
      })
      .join('<br>')
    lines.push(`| \`${id}\` | ${where} |`)
  }

  lines.push('')

  await writeFile(OUTPUT, lines.join('\n'), 'utf8')
  // eslint-disable-next-line no-console
  console.log(`[gen-testids] wrote ${sortedIds.length} testids to ${relative(REPO_ROOT, OUTPUT)}`)
}

main().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e)
  process.exit(1)
})
