name: Build

on:
  push:
    branches:
      - instance-share
    paths:
      - 'xmcl-runtime/**'
      - 'xmcl-runtime-api/**'
      - 'xmcl-keystone-ui/**'
      - 'xmcl-electron-app/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/**'

jobs:
  build-linux-arm64:
    runs-on: ubuntu-22.04
    name: linux arm64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: uraimo/run-on-arch-action@v2
        name: Build and deploy Maverick on Linux-ARM64
        id: build
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          shell: /bin/bash
          env: |
            CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_TOKEN }}
          install: |
            apt-get update -q -y
            apt-get install -q -y git
            apt install -q -y wget
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            wget http://launchpadlibrarian.net/611219191/libssl1.1_1.1.1f-1ubuntu2.16_arm64.deb
            dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_arm64.deb
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install 18.12.1
            nvm alias default 18.12.1
            nvm use default
            apt install -q -y npm
            npm install -g pnpm
          run: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use 18.12.1 && \
            pnpm install --filter=!./xmcl-page && \
            pnpm run --prefix xmcl-keystone-ui build && \
            pnpm run --prefix xmcl-electron-app build:all
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: linux-arm64
          path: |
            xmcl-electron-app/build/output/*.*