name: Core Package Publish

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.event.head_commit.message, 'chore(release)') }}

    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.sha }}
    - uses: pnpm/action-setup@v6
    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
    - name: Install
      run: |
        pnpm install --frozen-lockfile
      env:
        CI: true
    - name: Build
      run: |
        pnpm --parallel build:type
        pnpm --parallel build:cjs
        pnpm --parallel build:esm
        pnpm --parallel build:browser
    - name: Publish
      run: |
        pnpm -r --filter './packages/**' publish --access public --no-git-checks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Build Docs
      run: |
        pnpm build:docs
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: docs/
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
